# -*- coding: utf-8 -*-
"""
Created on Sat May 23 15:48:26 2026

@author: jpv88
"""

import numpy as np

jan_snap = np.array(['cctcgtaaatcctcatcaaaGAGCTCTGCCCTCATCAAAGATGGC',
            'CCCGAGGTTTCTTCTTCAATGCAACaaatcatccagtaaaccgcc',
            'cctcgtaaatcctcatcaaaCCGGGTAGGGAGGGAAGGAAAGACA',
            'CTGCAGGTAGCAAGAGTGGAGGAGCaaatcatccagtaaaccgcc',
            'cctcgtaaatcctcatcaaaAACCTTGTCTTCTCCGGAGGATGCT',
            'CAGCAAGTCAGTGGTGCTTCGTTAAaaatcatccagtaaaccgcc',
            'cctcgtaaatcctcatcaaaTGTTGCACGTTGGTTGGCTTCATCA',
            'GCAAATTTAACCACTTCCCAGCATCaaatcatccagtaaaccgcc',
            'cctcgtaaatcctcatcaaaCAGTAGCTCTGTGGAATGTCACAGT',
            'GCCTGACACCCTAAGAAAGGATTGTaaatcatccagtaaaccgcc',
            'cctcgtaaatcctcatcaaaTCTTGTCAGTATGCTACTGTCATGG',
            'CTTTGTTATTGTTGCTGTTGTGTGTaaatcatccagtaaaccgcc',
            'cctcgtaaatcctcatcaaaCTTGACAGTGTCCCAATACTGAGCA',
            'CTGCAGGTTTTGCTGGTATGACTTAaaatcatccagtaaaccgcc',
            'cctcgtaaatcctcatcaaaCCACATAGCAAGAGTATTGTCTCCA',
            'GCCAGACGTAGAAGATCTTCACGTTaaatcatccagtaaaccgcc',
            'cctcgtaaatcctcatcaaaTTCAACCAGCTGCAGCATGCGACGG',
            'AGTCCTGATGCCAGCATCTTTACTCaaatcatccagtaaaccgcc',
            'cctcgtaaatcctcatcaaaCCAGGCTTTTTTGTAAGCATCACTG',
            'GGCCACTACTCCATCCTGATTATTGaaatcatccagtaaaccgcc',
            'cctcgtaaatcctcatcaaaTGCGGATGAAGCCACCACTGATGGC',
            'CATTTTCCCGGGCATCATTTGTTACaaatcatccagtaaaccgcc',
            'cctcgtaaatcctcatcaaaATGGCGGAGGTTTCCGATGATGCCG',
            'AATCTCATTGCCCATGTCTAGAGCCaaatcatccagtaaaccgcc',
            'cctcgtaaatcctcatcaaaATCCTGTCGATCTGGCGATTCTGGG',
            'GTTTTGTTGGAATCAGCCTTCTCCAaaatcatccagtaaaccgcc'])

april_snap = np.array(['cctcgtaaatcctcatcaaaGAGCTCTGCCCTCATCAAAGATGGC',
                'CCCGAGGTTTCTTCTTCAATGCAACaaatcatccagtaaaccgcc',
                'cctcgtaaatcctcatcaaaCCGGGTAGGGAGGGAAGGAAAGACA',
                'CTGCAGGTAGCAAGAGTGGAGGAGCaaatcatccagtaaaccgcc',
                'cctcgtaaatcctcatcaaaAACCTTGTCTTCTCCGGAGGATGCT',
                'CAGCAAGTCAGTGGTGCTTCGTTAAaaatcatccagtaaaccgcc',
                'cctcgtaaatcctcatcaaaTGTTGCACGTTGGTTGGCTTCATCA',
                'GCAAATTTAACCACTTCCCAGCATCaaatcatccagtaaaccgcc',
                'cctcgtaaatcctcatcaaaCAGTAGCTCTGTGGAATGTCACAGT',
                'GCCTGACACCCTAAGAAAGGATTGTaaatcatccagtaaaccgcc',
                'cctcgtaaatcctcatcaaaTCTTGTCAGTATGCTACTGTCATGG',
                'CTTTGTTATTGTTGCTGTTGTGTGTaaatcatccagtaaaccgcc',
                'cctcgtaaatcctcatcaaaCTTGACAGTGTCCCAATACTGAGCA',
                'CTGCAGGTTTTGCTGGTATGACTTAaaatcatccagtaaaccgcc',
                'cctcgtaaatcctcatcaaaCCACATAGCAAGAGTATTGTCTCCA',
                'GCCAGACGTAGAAGATCTTCACGTTaaatcatccagtaaaccgcc',
                'cctcgtaaatcctcatcaaaTTCAACCAGCTGCAGCATGCGACGG',
                'AGTCCTGATGCCAGCATCTTTACTCaaatcatccagtaaaccgcc',
                'cctcgtaaatcctcatcaaaCCAGGCTTTTTTGTAAGCATCACTG',
                'GGCCACTACTCCATCCTGATTATTGaaatcatccagtaaaccgcc',
                'cctcgtaaatcctcatcaaaTGCGGATGAAGCCACCACTGATGGC',
                'CATTTTCCCGGGCATCATTTGTTACaaatcatccagtaaaccgcc',
                'cctcgtaaatcctcatcaaaATGGCGGAGGTTTCCGATGATGCCG',
                'AATCTCATTGCCCATGTCTAGAGCCaaatcatccagtaaaccgcc',
                'cctcgtaaatcctcatcaaaATCCTGTCGATCTGGCGATTCTGGG',
                'GTTTTGTTGGAATCAGCCTTCTCCAaaatcatccagtaaaccgcc'])

october_2025_snap = np.array(['cctcgtaaatcctcatcaaaGAGCTCTGCCCTCATCAAAGATGGC',
                    'CCCGAGGTTTCTTCTTCAATGCAACaaatcatccagtaaaccgcc',
                    'cctcgtaaatcctcatcaaaCCGGGTAGGGAGGGAAGGAAAGACA',
                    'CTGCAGGTAGCAAGAGTGGAGGAGCaaatcatccagtaaaccgcc',
                    'cctcgtaaatcctcatcaaaAACCTTGTCTTCTCCGGAGGATGCT',
                    'CAGCAAGTCAGTGGTGCTTCGTTAAaaatcatccagtaaaccgcc',
                    'cctcgtaaatcctcatcaaaTGTTGCACGTTGGTTGGCTTCATCA',
                    'GCAAATTTAACCACTTCCCAGCATCaaatcatccagtaaaccgcc',
                    'cctcgtaaatcctcatcaaaCAGTAGCTCTGTGGAATGTCACAGT',
                    'GCCTGACACCCTAAGAAAGGATTGTaaatcatccagtaaaccgcc',
                    'cctcgtaaatcctcatcaaaTCTTGTCAGTATGCTACTGTCATGG',
                    'CTTTGTTATTGTTGCTGTTGTGTGTaaatcatccagtaaaccgcc',
                    'cctcgtaaatcctcatcaaaCTTGACAGTGTCCCAATACTGAGCA',
                    'CTGCAGGTTTTGCTGGTATGACTTAaaatcatccagtaaaccgcc',
                    'cctcgtaaatcctcatcaaaCCACATAGCAAGAGTATTGTCTCCA',
                    'GCCAGACGTAGAAGATCTTCACGTTaaatcatccagtaaaccgcc',
                    'cctcgtaaatcctcatcaaaTTCAACCAGCTGCAGCATGCGACGG',
                    'AGTCCTGATGCCAGCATCTTTACTCaaatcatccagtaaaccgcc',
                    'cctcgtaaatcctcatcaaaCCAGGCTTTTTTGTAAGCATCACTG',
                    'GGCCACTACTCCATCCTGATTATTGaaatcatccagtaaaccgcc',
                    'cctcgtaaatcctcatcaaaTGCGGATGAAGCCACCACTGATGGC',
                    'CATTTTCCCGGGCATCATTTGTTACaaatcatccagtaaaccgcc',
                    'cctcgtaaatcctcatcaaaATGGCGGAGGTTTCCGATGATGCCG',
                    'AATCTCATTGCCCATGTCTAGAGCCaaatcatccagtaaaccgcc',
                    'cctcgtaaatcctcatcaaaATCCTGTCGATCTGGCGATTCTGGG',
                    'GTTTTGTTGGAATCAGCCTTCTCCAaaatcatccagtaaaccgcc'])

